---
title: ProfeMatesValencia.net
author: Ezequiel
email: marcel.soulodre@gmail.com
description: Aprende matemáticas, física y probabilidad & estadística conmigo.
baseurl: ''
url: profematesvalencia.net
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
